---
title: "Imtiyaaz"
output: html_document
date: "2022-11-03"
---
```{r}
library(tidyverse) # for data manipulations and visualisations
library(ggpubr) # for correlation coefficient on plot
library(gridExtra) # for arranging plots 
library(e1071) # for skewness
library(ggplot2)
library(dplyr)
library(tidyr)
library(readxl)
library(corrplot)
library(car)
library(DescTools)
library(glmnet)
```

```{r}
eval_results <- function(true, predict) {
  actual <- data.matrix(true)
  SSE <- sum((predict - actual)^2)
  SST <- sum((actual - mean(actual))^2)
  R_square <- 1 - SSE / SST
  data.frame(
    MSE = MSE(predict, true),
    MAE = MAE(predict, true),
    RMSE = RMSE(predict, true),
    MAPE = MAPE(predict, true),
    Rsquare = R_square
  )
}
```



```{r}
df <-read.csv('../data/countries1.csv')
df
subset1 <- df %>% select("pov","income","edu.total","hlth","mil","fdi","lbr.part","unemp","pop.gwth.total","pop.gwth.rural","gdp.dflt","gcf","trade","gdp.pc","lfdi","lgdp.dflt","lgdp.pc")
subset1
```



```{r}
set.seed(10)
index <- sort(sample(x = nrow(subset1), size = nrow(subset1)*.8))
train <- df[index, ]
test <- df[-index, ]
```







```{r}
lm.slr <- lm(pov ~ income+edu.total+hlth+mil+fdi+lbr.part+unemp+pop.gwth.total+pop.gwth.rural+gdp.dflt+gcf+trade+gdp.pc+lfdi+lgdp.dflt+lgdp.pc,data = train)
summary(lm.slr)

```
```{r}
subset1$income <- factor(subset1$income)
subset1$income <- as.numeric(subset1$income)


```


```{r}
str(subset1)
df0 <- subset1
scaler <- apply(X = df0, MARGIN = 2, FUN = sd)
subset1 <- as.data.frame(apply(df0, 2, function(x) x/sd(x, na.rm = TRUE)))
subset1
apply(subset1, 2, sd)

```
```{r}
model1 <- lm(pov ~ ., data = subset1)
summary(model1)
vif(model1)

```
```{r}
subset2 <- subset(subset1,select =c("pov","income","edu.total","hlth","mil","fdi","lbr.part","unemp","pop.gwth.total","pop.gwth.rural","gdp.dflt","gcf","trade","gdp.pc","lfdi","lgdp.dflt","lgdp.pc"))
subset2 <- na.omit(subset2)
train.x <- data.matrix(subset(subset2, select = -pov))
train.y = data.matrix(subset2$pov)
```

```{r}
corrplot(cor(subset2, use = "complete.obs"), 
         method = "number",
         type = "upper",
         tl.col = "black", 
         tl.srt = 30
         )
```

```{r}
set.seed(123)
rate <- 0.8
train.size <- round(nrow(subset2)*rate)
sample(sample(nrow(subset2), train.size))
training <- subset2[sample, ]
test <- subset2[-sample, ]

```
```{r}
model3 <- lm(pov ~., data = training)
summary(model3)

```

```{r}
fit <- model3$fitted.values
true <- training$pov
summary_MLR3_train <- eval_results(true, fit)
```

```{r}
fit <- predict(model3, newdata=test)
true <- test$pov
summary_MLR3_test <- eval_results(true, fit)
```



```{r}
summary_MLR <- rbind(summary_MLR3_train[-5], 
                     summary_MLR3_test[-5])
rownames(summary_MLR) <- c("Baseline MLR_Train", 
                           "Baseline MLR_Test" )
knitr::kable(summary_MLR, digits = 3)
```

```{r}
# Training Data
data <- training
train.x <- data.matrix(data[,-ncol(data)])
train.y <- data.matrix(data[,ncol(data)])

# Test Data
data <- test
test.x <- data.matrix(data[,-ncol(data)])
test.y <- data.matrix(data[,ncol(data)])
```

```{r}
# Fit Ridge Regression Model
set.seed(123)
cv_ridge <- cv.glmnet(train.x, train.y, alpha = 0)
glm_ridge <- glmnet(train.x, train.y, 
                    alpha = 0, lambda = cv_ridge$lambda.min)

# Evaluate Ridge Regression Model on Training Set
fit <- predict(glm_ridge, newx = train.x, type = "response")
true <- train.y
summary_ridge_train <- eval_results(true, fit)


# Evaluate Ridge Regression Model on Test Set
fit <- predict(glm_ridge, newx = test.x, type = "response")
true <- test.y
summary_ridge_test <- eval_results(true, fit)

# Summarise Ridge Regression Model Performance into Table
summary_ridge <- rbind(summary_ridge_train, summary_ridge_test)
rownames(summary_ridge) <- c("Ridge Model_Train", "Ridge Model_Test" )
```



```{r}
# Fit LASSO Model
set.seed(123)
cv_lasso <- cv.glmnet(train.x,train.y, alpha = 1)
glm_lasso <- glmnet(train.x,train.y, alpha = 1, 
                    lambda = cv_lasso$lambda.min)

# Evaluate LASSO Model on Training Set
fit <- predict(glm_lasso, newx = train.x)
true <- train.y
summary_lasso_train <- eval_results(true, fit)

# Evaluate LASSO Model on Test Set
fit <- predict(glm_lasso, newx = test.x)
true <- test.y
summary_lasso_test <- eval_results(true, fit)

# Summarise LASSO Model Performance into Table
summary_lasso <- rbind(summary_lasso_train, summary_lasso_test)
rownames(summary_lasso) <- c("LASSO Model_Train", "LASSO Model_Test" )
```


```{r}
summary_3models <- rbind(summary_MLR3_train, 
                         summary_ridge_train,                               
                         summary_lasso_train, 
                         summary_MLR3_test,                             
                         summary_ridge_test, 
                         summary_lasso_test)

rownames(summary_3models) <- c("Baseline MLR_Train", "Ridge Model_Train", 
                               "LASSO Model_Train",  "Baseline MLR_Test",  
                               "Ridge Model_Test", "LASSO Model_Test" )

knitr::kable(summary_3models[1:3,-5], digits = 3)
knitr::kable(summary_3models[4:6,-5], digits = 3)

```

```{r}
set.seed(123)
cv_ridge <- cv.glmnet(train.x, train.y, alpha = 0)
glm_ridge <- glmnet(train.x,
                    train.y,
                    alpha = 0,
                    lambda = cv_ridge$lambda.min)
t(coef(glm_ridge))

```


```{r}
train.x <- model.matrix(pov ~., data = training)[, -1]
train.y <- training$pov
test.x <- model.matrix(pov ~., data = test)[,-1]
test.y <- test$pov
```

```{r}
model_ridge_trial1 <- glmnet(train.x, train.y, alpha = 0, lambda = 0.1)
t(coef(model_ridge_trial1))
```

```{r}
model_ridge_trial2 <- glmnet(train.x, train.y, alpha = 0, lambda = 0.5)
t(coef(model_ridge_trial2))
```

```{r}
model_ridge_trial3 <- glmnet(train.x, train.y, alpha = 0, lambda = 1)
t(coef(model_ridge_trial3))
```


```{r}
table_summary <- cbind(coef(model_ridge_trial1),
                       coef(model_ridge_trial2),
                       coef(model_ridge_trial3))

colnames(table_summary) <- c("lambda = 0.1",
                             "lambda = 0.5",
                             "lambda = 1")

table_summary
```


```{r}
set.seed(123)
cv_lasso <- cv.glmnet(train.x,train.y, alpha = 1)
glm_lasso <- glmnet(train.x,train.y, 
                    alpha = 1, lambda = cv_lasso$lambda.min)
t(coef(glm_lasso))
```

```{r}
# Obtain performance of MLR model
fit <- model1$fitted.values
true <- subset2$pov
summary_model1 <- eval_results(true, fit)

# Obtain performance of ridge model
fit <- predict(glm_ridge, newx = train.x)
true <- train.y
summary_ridge <- eval_results(true, fit)

# Obtain performance of LASSO model
fit <- predict(glm_lasso, newx = train.x)
true <- train.y
summary_lasso <- eval_results(true, fit)

# Combine all performances into a single output
summary <- rbind(summary_model1, summary_ridge, summary_lasso)
rownames(summary) <- c("MLR", "Ridge_model", "LASSO_model" )
colnames(summary)[5] <- "R^2"
knitr::kable(summary, digits = 3)


```

```{r}
knitr::kable(summary_MLR, digits = 3)
knitr::kable(summary_ridge[,-5], digits = 3)
```

```{r}
# Fit Ridge Regression Model
set.seed(123)
cv_ridge <- cv.glmnet(train.x, train.y, alpha = 0)
glm_ridge <- glmnet(train.x, train.y, 
                    alpha = 0, lambda = cv_ridge$lambda.min)

# Evaluate Ridge Regression Model on Training Set
fit <- predict(glm_ridge, newx = train.x, type = "response")
true <- train.y
summary_ridge_train <- eval_results(true, fit)


# Evaluate Ridge Regression Model on Test Set
fit <- predict(glm_ridge, newx = test.x, type = "response")
true <- test.y
summary_ridge_test <- eval_results(true, fit)

# Summarise Ridge Regression Model Performance into Table
summary_ridge <- rbind(summary_ridge_train, summary_ridge_test)
rownames(summary_ridge) <- c("Ridge Model_Train", "Ridge Model_Test" )
```

```{r}
# Fit LASSO Model
set.seed(123)
cv_lasso <- cv.glmnet(train.x,train.y, alpha = 1)
glm_lasso <- glmnet(train.x,train.y, alpha = 1, 
                    lambda = cv_lasso$lambda.min)

# Evaluate LASSO Model on Training Set
fit <- predict(glm_lasso, newx = train.x)
true <- train.y
summary_lasso_train <- eval_results(true, fit)

# Evaluate LASSO Model on Test Set
fit <- predict(glm_lasso, newx = test.x)
true <- test.y
summary_lasso_test <- eval_results(true, fit)

# Summarise LASSO Model Performance into Table
summary_lasso <- rbind(summary_lasso_train, summary_lasso_test)
rownames(summary_lasso) <- c("LASSO Model_Train", "LASSO Model_Test" )
```

```{r}
summary_3models <- rbind(summary_MLR3_train, 
                         summary_ridge_train,                               
                         summary_lasso_train, 
                         summary_MLR3_test,                             
                         summary_ridge_test, 
                         summary_lasso_test)

rownames(summary_3models) <- c("Baseline MLR_Train", "Ridge Model_Train", 
                               "LASSO Model_Train",  "Baseline MLR_Test",  
                               "Ridge Model_Test", "LASSO Model_Test" )

knitr::kable(summary_3models[1:3,-5], digits = 3)
knitr::kable(summary_3models[4:6,-5], digits = 3)
```